# Generated by Django 2.0.13 on 2019-10-21 11:47

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('notifiable_id', models.PositiveIntegerField(verbose_name='Notifiable Id')),
                ('notifiable_type', models.CharField(max_length=255, verbose_name='Notifiable Type')),
                ('data', jsonfield.fields.JSONField(verbose_name='Data')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
